# Generated by Django 5.0.6 on 2024-07-05 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("User", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="is_active",
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
