# Generated by Django 5.0.6 on 2024-07-05 07:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Crop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="NotificationConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.TextField(blank=True, null=True)),
                (
                    "warning_level",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("color", models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="CropConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "parameter",
                    models.CharField(
                        choices=[
                            ("Temperature", "Temperature"),
                            ("Humidity", "Humidity"),
                            ("Soil Moisture", "Soil Moisture"),
                            ("Rainfall", "Rainfall"),
                            ("Light Intensity", "Light Intensity"),
                        ],
                        max_length=50,
                    ),
                ),
                ("good_min", models.FloatField()),
                ("good_max", models.FloatField()),
                ("tolerable_min", models.FloatField()),
                ("tolerable_max", models.FloatField()),
                ("bad_min", models.FloatField()),
                ("bad_max", models.FloatField()),
                (
                    "crop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="Config.crop"
                    ),
                ),
            ],
            options={
                "verbose_name": "Crop Parameter",
                "verbose_name_plural": "Crop Parameters",
                "unique_together": {("crop", "parameter")},
            },
        ),
    ]
