# Generated by Django 5.0.6 on 2024-07-05 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Config", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cropconfig",
            options={
                "verbose_name": "Crop Config",
                "verbose_name_plural": "Crop Config",
            },
        ),
        migrations.RenameField(
            model_name="cropconfig",
            old_name="bad_max",
            new_name="high_max",
        ),
        migrations.RenameField(
            model_name="cropconfig",
            old_name="bad_min",
            new_name="high_min",
        ),
        migrations.RenameField(
            model_name="cropconfig",
            old_name="good_max",
            new_name="low_max",
        ),
        migrations.RenameField(
            model_name="cropconfig",
            old_name="good_min",
            new_name="low_min",
        ),
    ]
