# Generated by Django 5.0.6 on 2024-07-05 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Config", "0002_alter_cropconfig_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="notificationconfig",
            name="parameter",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Temperature", "Temperature"),
                    ("Humidity", "Humidity"),
                    ("Soil Moisture", "Soil Moisture"),
                    ("Rainfall", "Rainfall"),
                    ("Light Intensity", "Light Intensity"),
                ],
                max_length=50,
                null=True,
            ),
        ),
    ]
