# Generated by Django 5.0.6 on 2024-07-05 06:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Device",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("device_id", models.CharField(max_length=50)),
                ("name", models.CharField(max_length=50)),
                ("location", models.CharField(max_length=50)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Device",
                "verbose_name_plural": "Devices",
            },
        ),
        migrations.CreateModel(
            name="DeviceStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("status", models.IntegerField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="Device.device"
                    ),
                ),
            ],
            options={
                "verbose_name": "Device Status",
                "verbose_name_plural": "Device Statuses",
            },
        ),
        migrations.CreateModel(
            name="HVACStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("status", models.BooleanField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="Device.device"
                    ),
                ),
            ],
            options={
                "verbose_name": "HVAC Status",
                "verbose_name_plural": "HVAC Statuses",
            },
        ),
        migrations.CreateModel(
            name="SensorData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("temperature", models.FloatField()),
                ("humidity", models.FloatField()),
                ("soil_moisture", models.FloatField()),
                ("rain_level", models.FloatField()),
                ("light_lux", models.FloatField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="Device.device"
                    ),
                ),
            ],
            options={
                "verbose_name": "Sensor Data",
                "verbose_name_plural": "Sensor Data",
            },
        ),
    ]
