# Generated by Django 5.0.6 on 2024-08-01 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Device", "0004_device_is_online_device_last_seen_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="devicestatus",
            name="status",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
