# Generated by Django 5.0.6 on 2024-08-01 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Device", "0005_alter_devicestatus_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hvacstatus",
            name="status",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
