# Generated by Django 5.0.6 on 2024-08-30 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Device", "0006_alter_hvacstatus_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sensordata",
            name="rain_level",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="sensordata",
            name="soil_moisture",
            field=models.IntegerField(),
        ),
    ]
