# Generated by Django 5.0.6 on 2024-08-30 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Device", "0007_alter_sensordata_rain_level_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sensordata",
            name="rain_level",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="sensordata",
            name="soil_moisture",
            field=models.FloatField(),
        ),
    ]
